<a href="https://colab.research.google.com/github/Zahid8/Pytorch-Geometric/blob/main/Backup_Graph_Neural_Networks_without_tags.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Thu Jun 16 13:26:56 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# Install required packages.
import os
import torch
os.environ['TORCH'] = torch.__version__
print(torch.__version__)

!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

# Helper function for visualization.
%matplotlib inline
import networkx as nx
import matplotlib.pyplot as plt


def visualize_graph(G, color):
    plt.figure(figsize=(7,7))
    plt.xticks([])
    plt.yticks([])
    nx.draw_networkx(G, pos=nx.spring_layout(G, seed=42), with_labels=False,
                     node_color=color, cmap="Set2")
    plt.show()


def visualize_embedding(h, color, epoch=None, loss=None):
    plt.figure(figsize=(7,7))
    plt.xticks([])
    plt.yticks([])
    h = h.detach().cpu().numpy()
    plt.scatter(h[:, 0], h[:, 1], s=140, c=color, cmap="Set2")
    if epoch is not None and loss is not None:
        plt.xlabel(f'Epoch: {epoch}, Loss: {loss.item():.4f}', fontsize=16)
    plt.show()

1.11.0+cu113


In [ ]:
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.11.0+cu113.html

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://data.pyg.org/whl/torch-1.11.0+cu113.html


In [ ]:
import os

com_wget = "sudo wget " +"https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_386.tar.gz"
com_unzip = "sudo tar -xzf gdrive_2.1.1_linux_386.tar.gz"
com_permission = "sudo chmod +x gdrive"
com_install_executor = "sudo install gdrive /usr/local/bin/gdrive"

os.system(com_wget)
os.system(com_unzip)
os.system(com_permission)
os.system(com_install_executor)

0

In [ ]:
!sudo gdrive list

Authentication needed
Go to the following url in your browser:
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=367116221053-7n0vf5akeru7on6o2fjinrecpdoe99eg.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=state

Enter verification code: 4/1AX4XfWgnB6p_5EA7beVj60q7XmUiG8qVLoQCcoUv2O1nB7y10yFO17qu8QU
Id                                  Name                    Type   Size      Created
10XzbooTnjys8yxcduTJpZaaDL6PbmLcb   slide3.xml              bin    2.2 KB    2022-02-10 08:02:09
1g1uruVRN_Cyg2gW_Zd7z9ZtlxdowfD7B   presentation.xml.rels   bin    4.7 KB    2022-02-10 08:02:15
10SIKJo-eOXyGcB7RWBIRoNf3eQrP8a32   image7.png              bin    15.4 KB   2022-02-10 08:01:54
1taMBfzvCb7trwKucsHKCn9fpi2fuI766   image9.png              bin    29.4 KB   2022-02-10 08:01:53
10lW8cXEKLpMVJgS0Y-O2B8zHQPAY5ppZ   slideLayout2.xml.rels   bin    311.0 B   2022-02-10 08:05:32

In [ ]:
!gdrive download 184NTddlP4LCoYNihyhZ6TnaEeRTpGfy8


Downloaded 184NTddlP4LCoYNihyhZ6TnaEeRTpGfy8 at 44.2 MB/s, total 44.2 MB


In [ ]:
import pandas as pd


In [ ]:
df = pd.read_csv("/content/playlist_data.csv")
df.head(10)

user_key  playlist_key  song_key artistname  \
0         0             0      1683  Anastacia   
1         0             0      1684  Anastacia   
2         0             0      1685  Anastacia   
3         0             0      1686  Anastacia   
4         0             0      1688  Anastacia   
5         0             0      1689  Anastacia   
6         0             0      1691  Anastacia   
7         0             0      1692  Anastacia   
8         0             0      1693  Anastacia   
9         0             0      1694  Anastacia   

                                 trackname                       playlistname  \
0                             Club Megamix  Anastacia – The Best of Anastacia   
1            Cowboys & Kisses - Radio Edit  Anastacia – The Best of Anastacia   
2                        Heavy on My Heart  Anastacia – The Best of Anastacia   
3                                     I Do  Anastacia – The Best of Anastacia   
4                             In Your Eyes  Anastacia – The Best of Anastacia   
5          Left Outside Alone - Radio Edit  Anastacia – The Best of Anastacia   
6                      Made For Lovin' You  Anastacia – The Best of Anastacia   
7                            Not That Kind  Anastacia – The Best of Anastacia   
8  One Day In Your Life - European Version  Anastacia – The Best of Anastacia   
9                             Paid My Dues  Anastacia – The Best of Anastacia   

                                       weighted_tags  
0  [('pop', 100), ('dance', 50), ('female vocalis...  
1  [('soul', 100), ('female', 50), ('pop', 50), (...  
2  [('pop', 100), ('female vocalists', 61), ('roc...  
3  [('pop', 100), ('female vocalists', 70), ('roc...  
4  [('pop', 86), ('female vocalists', 72), ('00s'...  
5  [('female vocalists', 100), ('pop', 72), ('par...  
6          [('pop', 100), ('female vocalists', 100)]  
7  [('pop', 100), ('female vocalists', 55), ('sou...  
8                    [('pop', 100), ('perlast', 50)]  
9  [('pop', 100), ('female vocalists', 58), ('roc...

In [ ]:
df=df.drop(['artistname','trackname','playlistname','weighted_tags'], axis=1)
df.head()

user_key  playlist_key  song_key
0         0             0      1683
1         0             0      1684
2         0             0      1685
3         0             0      1686
4         0             0      1688

In [ ]:
df.head()

user_key  playlist_key  song_key
0         0             0      1683
1         0             0      1684
2         0             0      1685
3         0             0      1686
4         0             0      1688

In [ ]:
df2=df
df2['s_key'] = df2['song_key']
df2['s_key'] = df2['s_key'].astype(str)
print(df2.dtypes)

user_key         int64
playlist_key     int64
song_key         int64
s_key           object
dtype: object


In [ ]:
df2=df2.groupby(['user_key', 'playlist_key'] ,as_index=False).agg({
    's_key': lambda x: ','.join(x),
})

df2.head(20)

user_key  playlist_key                                              s_key
0          0             0  1683,1684,1685,1686,1688,1689,1691,1692,1693,1...
1          0             1  9774,9800,9807,9818,9831,9834,9836,9837,9839,9...
2          0             2  71,2156,3059,3061,6245,7218,8443,8725,13280,14...
3          0             3  2156,2896,3028,4023,4256,6787,7265,8882,8970,9...
4          0             4  25203,25204,25215,25219,25227,25232,25235,2524...
5          0             5  27099,27101,27104,27107,27108,27111,27117,2712...
6          0             6  28229,28231,28244,28248,28258,28261,28265,2826...
7          0             7  783,1690,1856,3700,4194,5336,11039,12226,12241...
8          0             8  349,402,962,2156,2962,3060,5157,5322,5789,6714...
9          0             9  41233,41235,41237,41239,41240,41241,41242,4124...
10         0            10  461,1254,2368,7108,10469,10649,14629,15036,185...
11         0            11  2044,6184,6912,9116,9799,9948,15525,17233,1762...
12         0            12  3310,3481,5374,8973,9793,11268,12464,15839,203...
13         0            13  1035,1102,1641,6551,7315,8281,9530,9817,10361,...
14         1            14  883,884,11624,13781,13802,13990,14727,14739,15...
15         1            15  2747,5513,7501,9998,10363,11115,18206,18212,21...
16         1            16  2887,3882,5397,7216,12059,13871,13873,13875,13...
17         1            17  10755,10757,10758,10761,10762,10763,10764,1076...
18         1            18  7185,11361,11364,11368,11370,11371,11373,11376...
19         1            19  11402,11403,11404,11405,14165,14169,14174,1418...

In [ ]:
df2['s_key'] = df2['s_key'].str.split(',')

In [ ]:
df2.head()

user_key  playlist_key                                              s_key
0         0             0  [1683, 1684, 1685, 1686, 1688, 1689, 1691, 169...
1         0             1  [9774, 9800, 9807, 9818, 9831, 9834, 9836, 983...
2         0             2  [71, 2156, 3059, 3061, 6245, 7218, 8443, 8725,...
3         0             3  [2156, 2896, 3028, 4023, 4256, 6787, 7265, 888...
4         0             4  [25203, 25204, 25215, 25219, 25227, 25232, 252...

In [ ]:
for i, j in df2.iterrows():
    print(j[2])
    print()

Streaming output truncated to the last 5000 lines.
['165', '2395', '3782', '3843', '3844', '3847', '3849', '3850', '5476', '11510', '17038', '17047', '19074', '26013', '26021', '26030', '26035', '26047', '26069', '26078', '29556', '34780', '34784', '34789', '34792']

['650', '3359', '7311', '14589', '14590', '14593', '16918', '20760', '20776', '26052', '29592', '34654']

['19809', '19817', '19825', '19834', '19835', '19841', '19848', '19849', '19852', '19854', '19863', '19869', '19870', '19873', '19896', '29819', '29820', '29821', '29822', '29824', '29825', '29826', '29827', '29828', '29829', '29830', '29831', '29832']

['23698', '23700', '23701', '23702', '23704', '23706', '23707', '23708', '23709', '23710', '23711', '23712', '23713', '23714', '23718', '23719', '23721', '23722', '23723', '23724', '23726', '23727', '23728', '23729']

['2065', '6840', '7132', '7223', '7224', '7226', '7231', '7235', '15079', '19428', '25164', '25281', '25282', '25283', '26772', '30520', '45536', '45960']

In [ ]:
df2["identifier"] = df2['user_key'].astype(str) +","+df2["playlist_key"].astype(str)
df2['identifier'] = df2['identifier'].str.split(',')
df2=df2.drop(['user_key','playlist_key'], axis=1)

In [ ]:
df2.head()

s_key identifier
0  [1683, 1684, 1685, 1686, 1688, 1689, 1691, 169...     [0, 0]
1  [9774, 9800, 9807, 9818, 9831, 9834, 9836, 983...     [0, 1]
2  [71, 2156, 3059, 3061, 6245, 7218, 8443, 8725,...     [0, 2]
3  [2156, 2896, 3028, 4023, 4256, 6787, 7265, 888...     [0, 3]
4  [25203, 25204, 25215, 25219, 25227, 25232, 252...     [0, 4]

In [ ]:
for i, j in df2.iterrows():
    for x in range(len(j[0])):
        j[0][x] = int(j[0][x])
    for x in range(len(j[1])):
        j[1][x] = int(j[1][x])

In [ ]:
for i, j in df2.iterrows():
    print(j[0])
    print(j[1])

Streaming output truncated to the last 5000 lines.
[165, 2395, 3782, 3843, 3844, 3847, 3849, 3850, 5476, 11510, 17038, 17047, 19074, 26013, 26021, 26030, 26035, 26047, 26069, 26078, 29556, 34780, 34784, 34789, 34792]
[88, 924]
[650, 3359, 7311, 14589, 14590, 14593, 16918, 20760, 20776, 26052, 29592, 34654]
[88, 925]
[19809, 19817, 19825, 19834, 19835, 19841, 19848, 19849, 19852, 19854, 19863, 19869, 19870, 19873, 19896, 29819, 29820, 29821, 29822, 29824, 29825, 29826, 29827, 29828, 29829, 29830, 29831, 29832]
[88, 926]
[23698, 23700, 23701, 23702, 23704, 23706, 23707, 23708, 23709, 23710, 23711, 23712, 23713, 23714, 23718, 23719, 23721, 23722, 23723, 23724, 23726, 23727, 23728, 23729]
[89, 927]
[2065, 6840, 7132, 7223, 7224, 7226, 7231, 7235, 15079, 19428, 25164, 25281, 25282, 25283, 26772, 30520, 45536, 45960]
[89, 928]
[4916, 6096, 6097, 6098, 6099, 6100, 6101, 6102, 6103, 6104, 6105, 6106, 6107, 6108, 6109, 6110, 6111, 9210, 23739]
[89, 929]
[7220, 7221, 7222, 7225, 7226, 7227, 7229

In [ ]:
df2.head()

s_key identifier
0  [1683, 1684, 1685, 1686, 1688, 1689, 1691, 169...     [0, 0]
1  [9774, 9800, 9807, 9818, 9831, 9834, 9836, 983...     [0, 1]
2  [71, 2156, 3059, 3061, 6245, 7218, 8443, 8725,...     [0, 2]
3  [2156, 2896, 3028, 4023, 4256, 6787, 7265, 888...     [0, 3]
4  [25203, 25204, 25215, 25219, 25227, 25232, 252...     [0, 4]

In [ ]:
df2.to_csv("cleaned_dataset.csv")

In [ ]:
df3=df2 
df3['edge_pairs'] = df3.index
df3.head()

s_key identifier  edge_pairs
0  [1683, 1684, 1685, 1686, 1688, 1689, 1691, 169...     [0, 0]           0
1  [9774, 9800, 9807, 9818, 9831, 9834, 9836, 983...     [0, 1]           1
2  [71, 2156, 3059, 3061, 6245, 7218, 8443, 8725,...     [0, 2]           2
3  [2156, 2896, 3028, 4023, 4256, 6787, 7265, 888...     [0, 3]           3
4  [25203, 25204, 25215, 25219, 25227, 25232, 252...     [0, 4]           4

In [ ]:

for i, j in df3.iterrows():
    print(j[2][0])  

    #print(j[0])
    #print(j[1])

TypeError: ignored

In [ ]:
all_arr=[]
for i, j in df3.iterrows():
    all_arr.append(j[0])  

    #print(j[0])
    #print(j[1])

In [ ]:
print(df3['s_key'][1]) 

[9774, 9800, 9807, 9818, 9831, 9834, 9836, 9837, 9839, 9843, 13723, 21455]


In [ ]:

for i in range(len(all_arr)):
    temp_arr=[]
    a_set = set(all_arr[i])
    for j in range(i+1,len(all_arr)):
        val_arr = []
        b_set = set(all_arr[j])
        if(a_set & b_set):
            val_arr.append(i)
            val_arr.append(j)
        else:
            pass
        temp_arr.append(val_arr)
    #print("i : ",i," : ",temp_arr)
    df3['edge_pairs'][i]=temp_arr


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/usr/local/lib/python3.7/dist-packages/pandas/core/dtypes/cast.py:881: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' wh

In [ ]:
for i in range(len(df3['edge_pairs'])):
    df3['edge_pairs'][i]=[x for x in df3['edge_pairs'][i] if x]

In [ ]:
df3.head()

s_key identifier  \
0  [1683, 1684, 1685, 1686, 1688, 1689, 1691, 169...     [0, 0]   
1  [9774, 9800, 9807, 9818, 9831, 9834, 9836, 983...     [0, 1]   
2  [71, 2156, 3059, 3061, 6245, 7218, 8443, 8725,...     [0, 2]   
3  [2156, 2896, 3028, 4023, 4256, 6787, 7265, 888...     [0, 3]   
4  [25203, 25204, 25215, 25219, 25227, 25232, 252...     [0, 4]   

                                          edge_pairs  
0                                         [[0, 793]]  
1  [[1, 3], [1, 123], [1, 152], [1, 163], [1, 266...  
2  [[2, 3], [2, 8], [2, 9], [2, 123], [2, 133], [...  
3  [[3, 8], [3, 11], [3, 12], [3, 13], [3, 27], [...  
4  [[4, 215], [4, 322], [4, 342], [4, 793], [4, 1...

In [ ]:
df3.to_csv("dataset_final.csv")

In [ ]:
df3['edge_pairs'][0]

[[0, 793]]

In [ ]:
df3['identifier'][9][1]

9

In [ ]:
print(df3['edge_pairs'][2])

[[2, 3], [2, 8], [2, 9], [2, 123], [2, 133], [2, 207], [2, 352], [2, 397], [2, 480], [2, 490], [2, 600], [2, 641], [2, 663], [2, 664], [2, 773], [2, 774], [2, 775], [2, 878], [2, 900], [2, 950], [2, 974], [2, 986], [2, 994], [2, 1038], [2, 1149], [2, 1268], [2, 1335], [2, 1371], [2, 1416], [2, 1424], [2, 1428], [2, 1429], [2, 1433], [2, 1434], [2, 1440], [2, 1634], [2, 1709], [2, 1825], [2, 1983], [2, 2012], [2, 2062], [2, 2119], [2, 2126], [2, 2319], [2, 2349], [2, 2356], [2, 2380], [2, 2400], [2, 2443], [2, 2565], [2, 2642], [2, 2668], [2, 2743], [2, 2822], [2, 2864], [2, 2908], [2, 3021], [2, 3029], [2, 3075], [2, 3161], [2, 3320], [2, 3348], [2, 3413]]


In [ ]:
filename = "output_numbers.txt" #provide the file name

for i in range(len(df3['identifier'])):
    outfile = open(filename, 'a')
    for x in range (len(df3['edge_pairs'][i])):
        outfile.write(str(i) + '\n')

outfile.close() #Close the file when we’re done!

In [ ]:
for i in range(len(df3['edge_pairs'])):
    for j in range(len(df3['edge_pairs'][i])):
        for k in range(len(df3['edge_pairs'][i][j])-1):
            print(df3['edge_pairs'][i][j][k],",",df3['edge_pairs'][i][j][k+1])
            

0 , 793


AttributeError: ignored

In [ ]:
filename = "edges.txt" #provide the file name

for i in range(len(df3['edge_pairs'])):
    for j in range(len(df3['edge_pairs'][i])):
        for k in range(len(df3['edge_pairs'][i][j])-1):
            #print(df3['edge_pairs'][i][j][k],",",df3['edge_pairs'][i][j][k+1])
            outfile = open(filename,'a')
            outfile.write( str(df3['edge_pairs'][i][j][k])+","+str(df3['edge_pairs'][i][j][k+1])+'\n' ) 

outfile.close() #Close the file when we’re done!

In [ ]:
import numpy as np
#first arg = row 
#sec arf = column
my_arr = np.zeros((49293, 10), dtype=np.int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  after removing the cwd from sys.path.


In [ ]:
my_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
my_arr[0][0]

0

In [ ]:
for i in range(len(my_arr)):
    for j in range(len(my_arr[i])):
        print(my_arr[i])

Streaming output truncated to the last 5000 lines.
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 

KeyboardInterrupt: ignored

In [ ]:
filename = "node_attr.txt" #provide the file name

for i in range(len(my_arr)):
    for j in range(len(my_arr[i])):
        outfile = open(filename,'a')
        outfile.write(','.join(str(x) for x in my_arr[i])+"\n") 

outfile.close() #Close the file when we’re done!

In [ ]:
filename = "graph_label.txt" #provide the file name

for i in range(320):
    outfile = open(filename,'a')
    outfile.write(str("1")+"\n") 

outfile.close() #Close the file when we’re done!

In [ ]:
df4=df3 
df4['index'] = df4.index
df4.head()

s_key identifier  \
0  [1683, 1684, 1685, 1686, 1688, 1689, 1691, 169...     [0, 0]   
1  [9774, 9800, 9807, 9818, 9831, 9834, 9836, 983...     [0, 1]   
2  [71, 2156, 3059, 3061, 6245, 7218, 8443, 8725,...     [0, 2]   
3  [2156, 2896, 3028, 4023, 4256, 6787, 7265, 888...     [0, 3]   
4  [25203, 25204, 25215, 25219, 25227, 25232, 252...     [0, 4]   

                                          edge_pairs  index  weights  
0                                         [[0, 793]]      1        1  
1  [[1, 3], [1, 123], [1, 152], [1, 163], [1, 266...     48       48  
2  [[2, 3], [2, 8], [2, 9], [2, 123], [2, 133], [...     63       63  
3  [[3, 8], [3, 11], [3, 12], [3, 13], [3, 27], [...    214      214  
4  [[4, 215], [4, 322], [4, 342], [4, 793], [4, 1...     15       15

In [ ]:
df5=df4 
df5['weights'] = df5.index
df5.head()

s_key identifier  \
0  [1683, 1684, 1685, 1686, 1688, 1689, 1691, 169...     [0, 0]   
1  [9774, 9800, 9807, 9818, 9831, 9834, 9836, 983...     [0, 1]   
2  [71, 2156, 3059, 3061, 6245, 7218, 8443, 8725,...     [0, 2]   
3  [2156, 2896, 3028, 4023, 4256, 6787, 7265, 888...     [0, 3]   
4  [25203, 25204, 25215, 25219, 25227, 25232, 252...     [0, 4]   

                                          edge_pairs  index  weights  
0                                         [[0, 793]]      1        1  
1  [[1, 3], [1, 123], [1, 152], [1, 163], [1, 266...     48       48  
2  [[2, 3], [2, 8], [2, 9], [2, 123], [2, 133], [...     63       63  
3  [[3, 8], [3, 11], [3, 12], [3, 13], [3, 27], [...    214      214  
4  [[4, 215], [4, 322], [4, 342], [4, 793], [4, 1...     15       15

In [ ]:
for i in range(0,len(df5['edge_pairs'])):
    df5['weights'][i]=len(df5['edge_pairs'][i])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
df5['index'] = df5.index

df5=df5.reset_index()

df5.reset_index(inplace=True)


ValueError: ignored

In [ ]:
df5.head()

level_0                                              s_key identifier  \
0        1  [1683, 1684, 1685, 1686, 1688, 1689, 1691, 169...     [0, 0]   
1       48  [9774, 9800, 9807, 9818, 9831, 9834, 9836, 983...     [0, 1]   
2       63  [71, 2156, 3059, 3061, 6245, 7218, 8443, 8725,...     [0, 2]   
3      214  [2156, 2896, 3028, 4023, 4256, 6787, 7265, 888...     [0, 3]   
4       15  [25203, 25204, 25215, 25219, 25227, 25232, 252...     [0, 4]   

                                          edge_pairs  index  weights  
0                                         [[0, 793]]      0        1  
1  [[1, 3], [1, 123], [1, 152], [1, 163], [1, 266...      1       48  
2  [[2, 3], [2, 8], [2, 9], [2, 123], [2, 133], [...      2       63  
3  [[3, 8], [3, 11], [3, 12], [3, 13], [3, 27], [...      3      214  
4  [[4, 215], [4, 322], [4, 342], [4, 793], [4, 1...      4       15

In [ ]:
node_features = df5['s_key']
x = node_features.to_numpy()
x.shape # [num_nodes x num_features]

(3424,)

In [ ]:
# Convert to numpy
labels=df5['index']
y = labels.to_numpy()
y.shape # [num_nodes, 1] --> node regression

(3424,)

In [ ]:
edges=df5['edge_pairs']
edge_index = edges.to_numpy()
print(edge_index.shape)
print(edge_index.transpose())

(3424,)
[array([array(..., dtype=object),
        list([[1, 3], [1, 123], [1, 152], [1, 163], [1, 266], [1, 337], [1, 351], [1, 352], [1, 355], [1, 606], [1, 869], [1, 962], [1, 1125], [1, 1412], [1, 1413], [1, 1417], [1, 1435], [1, 1440], [1, 1454], [1, 1572], [1, 1588], [1, 1653], [1, 1726], [1, 1898], [1, 2075], [1, 2076], [1, 2166], [1, 2297], [1, 2299], [1, 2319], [1, 2327], [1, 2330], [1, 2335], [1, 2393], [1, 2395], [1, 2400], [1, 2405], [1, 2486], [1, 2523], [1, 2712], [1, 2811], [1, 2831], [1, 3022], [1, 3024], [1, 3109], [1, 3304], [1, 3305], [1, 3319]]),
        list([[2, 3], [2, 8], [2, 9], [2, 123], [2, 133], [2, 207], [2, 352], [2, 397], [2, 480], [2, 490], [2, 600], [2, 641], [2, 663], [2, 664], [2, 773], [2, 774], [2, 775], [2, 878], [2, 900], [2, 950], [2, 974], [2, 986], [2, 994], [2, 1038], [2, 1149], [2, 1268], [2, 1335], [2, 1371], [2, 1416], [2, 1424], [2, 1428], [2, 1429], [2, 1433], [2, 1434], [2, 1440], [2, 1634], [2, 1709], [2, 1825], [2, 1983], [2, 2012], [2,

In [ ]:
df5.head()

level_0                                              s_key identifier  \
0        1  [1683, 1684, 1685, 1686, 1688, 1689, 1691, 169...     [0, 0]   
1       48  [9774, 9800, 9807, 9818, 9831, 9834, 9836, 983...     [0, 1]   
2       63  [71, 2156, 3059, 3061, 6245, 7218, 8443, 8725,...     [0, 2]   
3      214  [2156, 2896, 3028, 4023, 4256, 6787, 7265, 888...     [0, 3]   
4       15  [25203, 25204, 25215, 25219, 25227, 25232, 252...     [0, 4]   

                                          edge_pairs  index  weights  
0                                         [[0, 793]]      0        1  
1  [[1, 3], [1, 123], [1, 152], [1, 163], [1, 266...      1       48  
2  [[2, 3], [2, 8], [2, 9], [2, 123], [2, 133], [...      2       63  
3  [[3, 8], [3, 11], [3, 12], [3, 13], [3, 27], [...      3      214  
4  [[4, 215], [4, 322], [4, 342], [4, 793], [4, 1...      4       15

In [ ]:
for i in df5['edge_pairs']:
    print(df5['edge_pairs'][1][2])

[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[1, 152]
[

In [ ]:
arr=[]
for i in range(0,len(df5['edge_pairs'])):
    for j in range(0,len(df5['edge_pairs'][i])):
        arr.append(df5['edge_pairs'][i][j])

In [ ]:
arr

[[0, 793],
 [1, 3],
 [1, 123],
 [1, 152],
 [1, 163],
 [1, 266],
 [1, 337],
 [1, 351],
 [1, 352],
 [1, 355],
 [1, 606],
 [1, 869],
 [1, 962],
 [1, 1125],
 [1, 1412],
 [1, 1413],
 [1, 1417],
 [1, 1435],
 [1, 1440],
 [1, 1454],
 [1, 1572],
 [1, 1588],
 [1, 1653],
 [1, 1726],
 [1, 1898],
 [1, 2075],
 [1, 2076],
 [1, 2166],
 [1, 2297],
 [1, 2299],
 [1, 2319],
 [1, 2327],
 [1, 2330],
 [1, 2335],
 [1, 2393],
 [1, 2395],
 [1, 2400],
 [1, 2405],
 [1, 2486],
 [1, 2523],
 [1, 2712],
 [1, 2811],
 [1, 2831],
 [1, 3022],
 [1, 3024],
 [1, 3109],
 [1, 3304],
 [1, 3305],
 [1, 3319],
 [2, 3],
 [2, 8],
 [2, 9],
 [2, 123],
 [2, 133],
 [2, 207],
 [2, 352],
 [2, 397],
 [2, 480],
 [2, 490],
 [2, 600],
 [2, 641],
 [2, 663],
 [2, 664],
 [2, 773],
 [2, 774],
 [2, 775],
 [2, 878],
 [2, 900],
 [2, 950],
 [2, 974],
 [2, 986],
 [2, 994],
 [2, 1038],
 [2, 1149],
 [2, 1268],
 [2, 1335],
 [2, 1371],
 [2, 1416],
 [2, 1424],
 [2, 1428],
 [2, 1429],
 [2, 1433],
 [2, 1434],
 [2, 1440],
 [2, 1634],
 [2, 1709],
 [2, 1825],


In [ ]:
d = [0]
df6 = pd.DataFrame(d,dtype=object)

In [ ]:
df6.head()

0
0  0

In [ ]:
df6[0][0] = arr

In [ ]:
df6.head()

0
0  [[0, 793], [1, 3], [1, 123], [1, 152], [1, 163...

In [ ]:
edges=df6
edge_index = edges.to_numpy()
print(edge_index.shape)
print(edge_index)

(1, 1)
[[list([[0, 793], [1, 3], [1, 123], [1, 152], [1, 163], [1, 266], [1, 337], [1, 351], [1, 352], [1, 355], [1, 606], [1, 869], [1, 962], [1, 1125], [1, 1412], [1, 1413], [1, 1417], [1, 1435], [1, 1440], [1, 1454], [1, 1572], [1, 1588], [1, 1653], [1, 1726], [1, 1898], [1, 2075], [1, 2076], [1, 2166], [1, 2297], [1, 2299], [1, 2319], [1, 2327], [1, 2330], [1, 2335], [1, 2393], [1, 2395], [1, 2400], [1, 2405], [1, 2486], [1, 2523], [1, 2712], [1, 2811], [1, 2831], [1, 3022], [1, 3024], [1, 3109], [1, 3304], [1, 3305], [1, 3319], [2, 3], [2, 8], [2, 9], [2, 123], [2, 133], [2, 207], [2, 352], [2, 397], [2, 480], [2, 490], [2, 600], [2, 641], [2, 663], [2, 664], [2, 773], [2, 774], [2, 775], [2, 878], [2, 900], [2, 950], [2, 974], [2, 986], [2, 994], [2, 1038], [2, 1149], [2, 1268], [2, 1335], [2, 1371], [2, 1416], [2, 1424], [2, 1428], [2, 1429], [2, 1433], [2, 1434], [2, 1440], [2, 1634], [2, 1709], [2, 1825], [2, 1983], [2, 2012], [2, 2062], [2, 2119], [2, 2126], [2, 2319], [2, 23

In [ ]:
print(edge_index.transpose())

[[list([[0, 793], [1, 3], [1, 123], [1, 152], [1, 163], [1, 266], [1, 337], [1, 351], [1, 352], [1, 355], [1, 606], [1, 869], [1, 962], [1, 1125], [1, 1412], [1, 1413], [1, 1417], [1, 1435], [1, 1440], [1, 1454], [1, 1572], [1, 1588], [1, 1653], [1, 1726], [1, 1898], [1, 2075], [1, 2076], [1, 2166], [1, 2297], [1, 2299], [1, 2319], [1, 2327], [1, 2330], [1, 2335], [1, 2393], [1, 2395], [1, 2400], [1, 2405], [1, 2486], [1, 2523], [1, 2712], [1, 2811], [1, 2831], [1, 3022], [1, 3024], [1, 3109], [1, 3304], [1, 3305], [1, 3319], [2, 3], [2, 8], [2, 9], [2, 123], [2, 133], [2, 207], [2, 352], [2, 397], [2, 480], [2, 490], [2, 600], [2, 641], [2, 663], [2, 664], [2, 773], [2, 774], [2, 775], [2, 878], [2, 900], [2, 950], [2, 974], [2, 986], [2, 994], [2, 1038], [2, 1149], [2, 1268], [2, 1335], [2, 1371], [2, 1416], [2, 1424], [2, 1428], [2, 1429], [2, 1433], [2, 1434], [2, 1440], [2, 1634], [2, 1709], [2, 1825], [2, 1983], [2, 2012], [2, 2062], [2, 2119], [2, 2126], [2, 2319], [2, 2349], [2

In [ ]:
from torch_geometric.data import Data
data = Data(x=x, edge_index=edge_index, y=y)

In [ ]:
data

Data(x=[3424], edge_index=[1, 1], y=[3424])

In [ ]:
from torch_geometric.utils import to_networkx

G = to_networkx(data, to_undirected=True)
visualize_graph(G, color=data.y)

/usr/local/lib/python3.7/dist-packages/torch_geometric/data/storage.py:276: UserWarning: Unable to accurately infer 'num_nodes' from the attribute set '{'edge_index', 'x', 'y'}'. Please explicitly set 'num_nodes' as an attribute of 'data' to suppress this warning
  " to suppress this warning")


TypeError: ignored

In [ ]:
import itertools
import numpy as np

teams = fifa_df["str_team_name"].unique()
all_edges = np.array([], dtype=np.int32).reshape((0, 2))
for team in teams:
    team_df = fifa_df[fifa_df["str_team_name"] == team]
    players = team_df["int_player_id"].values
    # Build all combinations, as all players are connected
    permutations = list(itertools.combinations(players, 2))
    edges_source = [e[0] for e in permutations]
    edges_target = [e[1] for e in permutations]
    team_edges = np.column_stack([edges_source, edges_target])
    all_edges = np.vstack([all_edges, team_edges])
# Convert to Pytorch Geometric format
edge_index = all_edges.transpose()
edge_index # [2, num_edges]